# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_auto_20160222_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
